### PR TITLE
Metadata exclusion filter

### PR DESCRIPTION
**Pull request by tinenbruno**
This PR aims to add a metadata exclusion filter, in addition to the inclusion filter existent today.

## Use case
You want your worker application to log on a separated file, so you can better filter it in your logging service (e.g. papertrail). Instead of doing a logger with an inclusion filter with the worker and another one with all the other apps, you just need to exclude the worker application from the other app.

## Usage
```
config :logger, :ui,
  path: "/path/to/ui.log",
  level: :info,
  metadata_exclusion_filter: [application: :ui]
```

### CODE REVIEW

**Comment by JayDadhania** [comment]
Any updates on this?

**Comment by fireproofsocks** [comment]
Unless I am misunderstanding, this more or less duplicates functionality in PR #66

**Comment by fireproofsocks** [comment]
I'm still getting familiar with the repo but I now have permissions to publish, so I can help things move.  If it's possible it'd be great if you could resolve the conflicts.  Thanks for your input!

**Comment by fireproofsocks** [comment]
Closing this in favor of PR #80

**Pull request closed without merging**
