### PR TITLE
rotate log files

### PR DESCRIPTION
**Pull request by sawater**
I think it would be nicer if  this "logger_file_backend"  provide simple way to rotate log files.
File.stat can get inode and file size at the same time, so line 62 could be optimized.

### CODE REVIEW

**Comment by sawater** [comment]
```
config :logger,
  backends: [{LoggerFileBackend, :error_log}]

config :logger, :error_log,
  path: "/tmp/error.log",
  level: :debug,
  rotate: %{max_bytes: 1024, keep: 3}
```
This config will work.

**Comment by onkel-dirtus** [comment]
Thanks for the feature. I rebased your branch and merged in in v0.0.10.

**Comment by danturn** [comment]
hey guys, 

does the log rotation work on windows?

**Comment by noggenfogger86** [comment]
yes. it works.

**Comment by OvermindDL1** [comment]
Where is this documented at?  The Readme states the functionality does not exist, what it removed?

**Comment by andreapavoni** [comment]
@OvermindDL1 stumbled upon this comment because I was looking for something similar. The [feature exists](https://github.com/onkel-dirtus/logger_file_backend/search?q=rotate&unscoped_q=rotate), but it looks like it isn't documented.

**Pull request closed without merging**
