### PR TITLE
Misc doc changes

### PR DESCRIPTION
**Pull request by kianmeng**
Besides other documentation changes, this commit ensures the generated
HTML doc for HexDocs.pm will become the source of truth for this Elixir
library and leverage on latest features of ExDoc.

### CODE REVIEW

**Comment by fireproofsocks** [comment]
Thanks!  Although I have have write access to the repo, I can't actually push updates to hex until Issue #75 gets resolved.  I have contacted hex support and tried to draw attention to it in hopes that it can be quickly resolved, otherwise, we'll have to fork the repo and publish under a separate package name.

**Comment by kianmeng** [comment]
@fireproofsocks Any updates on this?

**Comment by fireproofsocks** [comment]
Unfortunately, no updates.  I reached out to @onkel-dirtus re transferring ownership in Hex; I also emailed support @ hex.pm re transferring ownership, but I never heard back from anyone -- maybe if you or someone else knows someone over there they could help move this along? 

Or maybe it's time to cut the chords and publish a fork that can be maintained?

**Comment by kianmeng** [comment]
> Unfortunately, no updates. I reached out to @onkel-dirtus re transferring ownership in Hex; I also emailed support @ hex.pm re transferring ownership, but I never heard back from anyone -- maybe if you or someone else knows someone over there they could help move this along?

Thanks for the context, but I don't have the contacts of anyone who can look into this.

> Or maybe it's time to cut the chords and publish a fork that can be maintained?

Probably that would be the next best step.

**Comment by kianmeng** [comment]
:tada: :tada: :tada: :tada: :tada:

**Pull request merged**
